services:
  web:
    image: project/nginx-prod:1.0.0
    build:
      context: ../shared/nginx
    ports:
      - "8080:80"
    volumes:
      - project_files_stage:/app
    networks:
      - internal

  php-fpm:
    image: project/php-fpm-composer:1.0.0
    build:
      context: ../shared/php-fpm
    env_file:
      - .env
    volumes:
      - project_files_stage:/app
    networks:
      - internal

  database:
    image: mariadb
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ../../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_data_stage:/var/lib/mysql
    networks:
      - internal

volumes:
  database_data_stage:
  project_files_stage:

networks:
  internal:
    driver: bridge
