services:
  web:
    image: project/nginx-prod:1.0.0
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - project_files:/app
    networks:
      - internal

  php-fpm:
    image: project/php-fpm-composer:1.0.0
    build:
      context: .docker/shared/php-fpm
    volumes:
      - project_files:/app
    networks:
      - internal

  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_data:/var/lib/mysql
    networks:
      - internal

volumes:
  database_data:
  project_files:

networks:
  internal:
    driver: bridge
