services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx:/etc/nginx/templates
      - ./:/var/www/html
    networks:
      - internal

  php:
    image: php-fpm-composer:1.0.0
    build:
      context: ./.docker/fpm
    volumes:
      - ./:/var/www/html
    networks:
      - internal

networks:
  internal:
    driver: bridge
