services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx:/etc/nginx/templates
      - ./:/var/www/html
    networks:
      - internal

  php:
    image: php-fpm-composer:1.0.0
    build:
      context: ./.docker/fpm
    volumes:
      - ./:/var/www/html
    networks:
      - internal

  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - internal

networks:
  internal:
    driver: bridge
