services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx:/etc/nginx/templates
      - ./:/var/www/html
    networks:
      - internal

  php-fpm:
    image: project/php-fpm-composer:1.0.0
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - internal

  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - internal

  scss-compiler:
    image: project/scss-compiler:1.0.0
    build:
      context: ./.docker/sass-compiler
    volumes:
      - ./style:/app/input
      - ./public/style:/app/output

volumes:
  data:

networks:
  internal:
    driver: bridge
